#!/usr/bin/env python3
"""Generate or check the cross-language vectors for the first-pass wire format.

Python's json module defines the version-1 wire format that first_pass.py
encode() writes; convex/lib/wireJson.ts must reproduce it exactly, so the
backend accepts only bytes that first_pass.py restore can rebuild. Each vector
pairs an input spelling with Python's canonical encoding of the same value.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VECTORS = HERE / 'fixtures' / 'wire-format-vectors.json'

NUMBERS = [
    '1e-7', '1E-7', '1e-07', '0.0000001', '2.5e-5', '-2.5e-10', '0.0001', '0.00001', '0.1',
    '0.30000000000000004', '1.5', '1.50', '3.14159', '12345.678', '123', '123.0', '123e0',
    '0', '-0', '0.0', '-0.0', '1e15', '1000000000000000.0', '1e16', '1e+16', '10000000000000000.0',
    '1e21', '1e22', '1e100', '5e-324', '1.7976931348623157e308', '123456789012345678',
    '123456789012345678.0', '9007199254740993', '9007199254740993.0', '-43', '-43.0', '172.0',
]

DOCUMENTS = [
    '{"b":1,"a":2}',
    '{ "a" : [ 1 , 2.0 ] ,\n "c" : null }',
    '{"t":true,"f":false,"n":null,"e":{},"l":[]}',
    '"café"',
    '"\\u00e9 and \\ud83d\\ude00"',
    '"slash \\/ and / tab \\t newline \\n cr \\r backspace \\b formfeed \\f"',
    '"delete \\u007f and quote \\" and backslash \\\\"',
    '{"\\ue000":1,"\\ud83d\\ude00":2,"z":3,"A":4}',
    '{"k":"\\u0001"}',
    '[1e-7,{"cost_usd":1e-7,"latitude":-43.0,"n":1}]',
]

REJECTED = [
    '{"a":1,"a":2}',
    'NaN',
    'Infinity',
    '1e400',
    '[1,]',
    '{"a":1} x',
    '01',
    '"unterminated',
]


def canonical(text):
    return json.dumps(json.loads(text), sort_keys=True, ensure_ascii=True,
                      separators=(',', ':'), allow_nan=False)


def build():
    return {
        'description': 'Generated by scripts/agent_research/wire_vectors.py; Python json.dumps(sort_keys=True, ensure_ascii=True, separators=(",", ":"), allow_nan=False) of each input. Checked by test_first_pass.py and convex/lib/wireJson.node-test.mjs.',
        'canonical': [{'input': text, 'expected': canonical(text)} for text in NUMBERS + DOCUMENTS],
        'rejected': REJECTED,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args(argv)
    raw = json.dumps(build(), indent=2, ensure_ascii=True) + '\n'
    if args.check:
        if not VECTORS.exists() or VECTORS.read_text() != raw:
            print('wire-format vectors are stale; run scripts/agent_research/wire_vectors.py', file=sys.stderr)
            return 1
        return 0
    VECTORS.write_text(raw)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
