// the version-1 wire format of the first-pass archive, reproduced exactly:
// python's json.dumps(value, sort_keys=True, ensure_ascii=True,
// separators=(",", ":"), allow_nan=False), which scripts/agent_research/
// first_pass.py encode() writes before appending one newline. the backend
// re-encodes submitted text with canonicalWireJson and accepts it only when
// the result equals the bytes, so every stored receipt restores through
// first_pass.py restore. the cross-language vectors in
// scripts/agent_research/fixtures/wire-format-vectors.json are generated by
// python and checked by both test suites.
//
// javascript's JSON.parse forgets whether a number was written as an integer
// or a float, and python keeps that distinction (1 stays 1, 1.0 stays 1.0),
// so this is a small parser over the source text, not a re-encoding of a
// parsed value.

const MAX_DEPTH = 64;
const NUMBER = /-?(?:0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?/y;

// repr() of a python float: the shortest round-trip digits (the same digits
// javascript chooses), in fixed notation for decimal exponents from -4 to
// 15 with a trailing ".0" when integral, otherwise as d[.ddd]e±XX
export function pythonFloatRepr(value: number): string {
  if (!Number.isFinite(value)) throw new Error("non-finite JSON number");
  if (value === 0) return Object.is(value, -0) ? "-0.0" : "0.0";
  const sign = value < 0 ? "-" : "";
  const [mantissa, exponentText] = Math.abs(value).toExponential().split("e");
  const digits = mantissa.replace(".", "");
  const exponent = Number(exponentText);
  // python's decpt: the decimal point sits after this many digits
  const point = exponent + 1;
  if (point > -4 && point <= 16) {
    if (point <= 0) return `${sign}0.${"0".repeat(-point)}${digits}`;
    if (point < digits.length) return `${sign}${digits.slice(0, point)}.${digits.slice(point)}`;
    return `${sign}${digits}${"0".repeat(point - digits.length)}.0`;
  }
  const head = digits.length > 1 ? `${digits[0]}.${digits.slice(1)}` : digits;
  const magnitude = String(Math.abs(exponent)).padStart(2, "0");
  return `${sign}${head}e${exponent < 0 ? "-" : "+"}${magnitude}`;
}

// python's ensure_ascii string encoding: escapes for quote, backslash and
// the five short controls, \u00xx for other controls, and \uxxxx (lowercase,
// surrogate pairs above the basic plane) for everything outside 0x20-0x7e
export function pythonString(value: string): string {
  return JSON.stringify(value).replace(/[\u007f-￿]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`);
}

// python sorts str keys by code point; javascript's default sort compares
// utf-16 units, which differs above the basic plane
function compareCodePoints(left: string, right: string): number {
  const a = Array.from(left, (c) => c.codePointAt(0)!);
  const b = Array.from(right, (c) => c.codePointAt(0)!);
  for (let i = 0; i < Math.min(a.length, b.length); i += 1) {
    if (a[i] !== b[i]) return a[i] - b[i];
  }
  return a.length - b.length;
}

// parse json text and return python's canonical encoding of the same value
// (without the final newline). duplicate keys and non-finite numbers are
// refused, as the archive's parser refuses them. when floatPaths is given it
// receives the path of every number python reads as a float, in the path
// notation of lib/agentIntake schemaCheck ($, .key, [index]), so a schema
// check over the parsed value can apply python's int/float distinction.
export function canonicalWireJson(text: string, floatPaths?: Set<string>): string {
  let at = 0;
  const skip = () => { while (at < text.length && " \t\n\r".includes(text[at])) at += 1; };
  const fail = (message: string): never => { throw new Error(`${message} at offset ${at}`); };
  const expect = (literal: string) => { if (text.startsWith(literal, at)) at += literal.length; else fail(`expected ${literal}`); };
  const readString = (): string => {
    const start = at;
    at += 1;
    while (at < text.length && text[at] !== '"') at += text[at] === "\\" ? 2 : 1;
    if (at >= text.length) fail("unterminated string");
    at += 1;
    try {
      return JSON.parse(text.slice(start, at)) as string;
    } catch {
      return fail("invalid string");
    }
  };
  const value = (depth: number, path: string): string => {
    if (depth > MAX_DEPTH) fail("JSON exceeds depth limit");
    skip();
    const c = text[at];
    if (c === "{") {
      at += 1;
      const members: Array<[string, string]> = [];
      const seen = new Set<string>();
      skip();
      if (text[at] === "}") { at += 1; return "{}"; }
      for (;;) {
        skip();
        if (text[at] !== '"') fail("expected object key");
        const key = readString();
        if (seen.has(key)) fail("duplicate JSON object key");
        seen.add(key);
        skip();
        expect(":");
        members.push([key, value(depth + 1, `${path}.${key}`)]);
        skip();
        if (text[at] === ",") { at += 1; continue; }
        expect("}");
        break;
      }
      members.sort(([left], [right]) => compareCodePoints(left, right));
      return `{${members.map(([key, encoded]) => `${pythonString(key)}:${encoded}`).join(",")}}`;
    }
    if (c === "[") {
      at += 1;
      const items: string[] = [];
      skip();
      if (text[at] === "]") { at += 1; return "[]"; }
      for (;;) {
        items.push(value(depth + 1, `${path}[${items.length}]`));
        skip();
        if (text[at] === ",") { at += 1; continue; }
        expect("]");
        break;
      }
      return `[${items.join(",")}]`;
    }
    if (c === '"') return pythonString(readString());
    if (text.startsWith("true", at)) { at += 4; return "true"; }
    if (text.startsWith("false", at)) { at += 5; return "false"; }
    if (text.startsWith("null", at)) { at += 4; return "null"; }
    NUMBER.lastIndex = at;
    const match = NUMBER.exec(text);
    if (match === null || match[0] === "" || match[0] === "-") return fail("invalid JSON value");
    at += match[0].length;
    const lexeme = match[0];
    if (match[1] === undefined && match[2] === undefined) {
      // a python int keeps its digits; -0 parses as 0
      return lexeme === "-0" ? "0" : lexeme;
    }
    floatPaths?.add(path);
    return pythonFloatRepr(Number(lexeme));
  };
  const encoded = value(0, "$");
  skip();
  if (at !== text.length) fail("trailing text after JSON value");
  return encoded;
}

// true when the text is already exactly the archive's bytes for its value
export function isCanonicalWireJson(text: string): boolean {
  if (!text.endsWith("\n")) return false;
  try {
    return canonicalWireJson(text.slice(0, -1)) === text.slice(0, -1);
  } catch {
    return false;
  }
}
