import json, copy

# derived per-vintage views of the committed product
# apps/regions/ee/data/area_summary_county.json: the runtime's per-level
# summary loader reads only the "rows" array for a given censusLevels
# entry, and store.years is derived solely from the rows present in
# that file. because 2000, 2011, and 2021 use separate period county
# boundary vintages that must never cross-paint (no cross-wave county
# concordance is built), each census level needs its own summary file
# carrying only its own year. this script does not modify the committed
# product; it writes three filtered companion files consumed only by
# apps/regions/ee/index.html. the pattern follows
# scripts/build_de_level_summaries.py.

SRC = "apps/regions/ee/data/area_summary_county.json"

with open(SRC) as f:
    d = json.load(f)

for year, suffix, boundary_set_id, source_dataset_id in [
    (2000, "2000", "ee-county-2000-maaamet", "maaamet-historical-county-2000-12-04"),
    (2011, "2011", "ee-county-2011-maaamet", "maaamet-historical-county-2011-06-08"),
    (2021, "2021", "ee-county-2021-maaamet", "maaamet-historical-county-2021-01-01"),
]:
    out = copy.deepcopy(d)
    out["rows"] = [r for r in d["rows"] if r["year"] == year]
    out["boundary_set"] = {
        **d["boundary_set"],
        "boundary_set_id": boundary_set_id,
        "vintage": f"{year} period county vintage",
        "source_dataset_id": source_dataset_id,
    }
    out["_derived_view_notice"] = (
        f"Derived view of {SRC} (committed), filtered to the {year} "
        f"county rows only; the region-map runtime's per-level year "
        f"list therefore never offers another vintage's year for this "
        f"boundary set. Generated by scripts/build_ee_level_summaries.py; not an "
        f"independent data product. Regenerate from the committed "
        f"source if it changes."
    )
    dest = f"apps/regions/ee/data/area_summary_county_{suffix}.json"
    with open(dest, "w") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(dest, len(out["rows"]), "rows")
