#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["shapely>=2.0"]
# ///
"""Build the world outline manifest the global map's Contribute entry reads.

Writes apps/shared/data/world-outlines.json in the region-bboxes.json format
(code, name, boxes, rings) for every country that has NO page under
apps/regions/: the page manifest keeps precedence for the 100 page
countries (exact boundaries, including the island states 1:110m omits).
Geometry comes from Natural Earth 1:110m admin-0 and is simplified with the
page manifest's own ring simplifier, so the shared resolver
(apps/shared/region-resolve.js) reads both manifests alike.

Run:
    uv run scripts/build_world_outlines.py
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path

from shapely import make_valid
from shapely.geometry import shape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_region_bboxes import cluster_boxes, feature_extent, outline_rings, walk_coords  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
PAGE_MANIFEST = REPO / "apps/regions/_shared/data/region-bboxes.json"
REGISTRY = REPO / "apps/shared/data/country-registry.json"
OUT = REPO / "apps/shared/data/world-outlines.json"
NE_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson"
NE_CACHE = Path(os.environ.get("POW_SCRATCH", "/tmp")) / "ne_110m_admin_0_countries.geojson"
PROJECT_CODE_FOR_ISO = {"gb": "uk"}


def load_ne():
    if not NE_CACHE.exists():
        NE_CACHE.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(NE_URL, NE_CACHE)
    return json.loads(NE_CACHE.read_text(encoding="utf-8"))


def main():
    page_codes = {r["code"] for r in json.loads(PAGE_MANIFEST.read_text(encoding="utf-8"))["regions"]}
    names = {c["code"]: c["name"] for c in json.loads(REGISTRY.read_text(encoding="utf-8"))["countries"]}
    regions = []
    for feature in load_ne()["features"]:
        props = feature["properties"]
        iso = (props.get("ISO_A2_EH") or "").strip().lower()
        if not iso or iso == "-99":
            continue
        code = PROJECT_CODE_FOR_ISO.get(iso, iso)
        if code in page_codes:
            continue
        coords = []
        walk_coords(feature["geometry"]["coordinates"], coords)
        geom = make_valid(shape(feature["geometry"]))
        polys = [geom] if geom.geom_type == "Polygon" else list(geom.geoms) if geom.geom_type == "MultiPolygon" else []
        if not polys:
            continue
        boxes = cluster_boxes([feature_extent(coords)])
        rings = outline_rings(polys)
        regions.append({"code": code, "name": names.get(code, props.get("NAME_EN") or props["ADMIN"]), "boxes": boxes, "rings": rings})
    regions.sort(key=lambda r: r["code"])
    OUT.write_text(
        json.dumps({"note": "generated by scripts/build_world_outlines.py from natural earth 1:110m admin-0 for countries without a page under apps/regions/; same format as region-bboxes.json (boxes [west, south, east, north], west > east wrapping the antimeridian; even-odd outline rings whose longitudes may run past 180)", "regions": regions}, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(REPO)}: {len(regions)} countries, {OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
