import json, copy

# derived per-vintage views of the committed product
# apps/regions/de/data/area_summary_kreis.json: the runtime's per-level
# summary loader reads only the "rows" array for a given censusLevels
# entry, and store.years is derived solely from the rows present in
# that file. because 2011 (412 kreise) and 2022 (400 kreise) use
# separate period boundary vintages that must never cross-paint, each
# census level needs its own summary file carrying only its own year.
# this script does not modify the committed product; it writes two
# filtered companion files consumed only by apps/regions/de/index.html.

SRC = "apps/regions/de/data/area_summary_kreis.json"

with open(SRC) as f:
    d = json.load(f)

for year, suffix, boundary_set_id in [
    (2011, "2011", "de-kreis-2011-bkg-vg250"),
    (2022, "2022", "de-kreis-2022-bkg-vg250"),
]:
    out = copy.deepcopy(d)
    out["rows"] = [r for r in d["rows"] if r["year"] == year]
    out["boundary_set"] = {
        **d["boundary_set"],
        "vintage": f"{year} period Kreis vintage",
        "source_dataset_id": boundary_set_id,
    }
    out["_derived_view_notice"] = (
        f"Derived view of {SRC} (committed d024896), filtered to the "
        f"{year} Kreis rows only, so the region-map runtime's per-level "
        f"year list never offers the other vintage's year for this "
        f"boundary set. Generated by scripts/build_de_level_summaries.py; "
        f"not an independent data product. Regenerate from the committed "
        f"source if it changes."
    )
    dest = f"apps/regions/de/data/area_summary_kreis_{suffix}.json"
    with open(dest, "w") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(dest, len(out["rows"]), "rows")
